# ==============================================
# declaratives.yml - IoT Swarm Stack Deployment 
# ==============================================

- hosts: manager
  become: yes
  vars_files:
    - vars/declarative.yml
    - vars/secrets.yml

  tasks:
    # ---------------------------
    # 1. Ensure deployment directory
    # ---------------------------
    - name: Create directory for declarative stack files
      file:
        path: /home/ubuntu/iot_declarative
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    # ---------------------------
    # 2. Template the IoT stack YAML
    # ---------------------------
    - name: Template Swarm stack file (Compose v3.9)
      template:
        src: templates/iot_stack.yml.j2
        dest: /home/ubuntu/iot_declarative/iot_stack.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    # ---------------------------
    # 3. Ensure overlay network exists
    # ---------------------------
    - name: Wait until overlay network iot_net is visible
      shell: docker network inspect iot_net --format '{{"{{"}}.Name{{"}}"}}'
      register: network_check
      retries: 5
      delay: 5
      until: network_check.rc == 0
      changed_when: false

    # ---------------------------
    # 4. Deploy the IoT stack on the manager
    # ---------------------------
    - name: Deploy IoT Swarm stack
      community.docker.docker_stack:
        name: iot_stack
        state: present
        compose:
          - /home/ubuntu/iot_declarative/iot_stack.yml

    # ---------------------------
    # 5. Smoke Test: Show Swarm services
    # ---------------------------
    - name: Show running Swarm services
      shell: docker service ls
      register: swarm_services
      changed_when: false

    - debug:
        var: swarm_services.stdout_lines

    # ---------------------------
    # 6. Smoke Test: Processor logs
    # ---------------------------
    - name: Check processor logs
      shell: docker service logs --tail 20 iot_stack_processor || true
      register: processor_logs
      changed_when: false

    - debug:
        var: processor_logs.stdout_lines

    # ---------------------------
    # 7. Smoke Test: Verify Mongo insert count
    # ---------------------------
    - name: Verify Mongo document count
      shell: |
        cid=$(docker ps -qf "name=iot_stack_mongo")
        [ -n "$cid" ] && docker exec "$cid" mongosh --quiet --eval \
          "db.getSiblingDB('transactions_db').transactions.countDocuments()" \
          || echo "mongo container not running"
      register: mongo_count
      changed_when: false

    - debug:
        var: mongo_count.stdout_lines
